### PR TITLE
Enhanced README

### PR DESCRIPTION
**Pull request by rbo13**
README improvements:
- Fixed typo
- Added installing dependencies
- Added running the application

ref: #5 

Signed-off-by: Richard Burk Orofeo <chardy.orofeo@yahoo.com.ph>

### CODE REVIEW

**Comment by Variable2016** [comment]
@rbo13 Thank you :hamburger: 

We can do more :smile:

**Comment by rbo13** [comment]
@Variable2016 thats all I can add for the meantime though 👍 if you got something, you can add also :)

**Comment by Yusadolat** [comment]
Thank you @rbo13 

It's well appreciated :raised_hands:

**Comment by rbo13** [comment]
You are welcome @Yusadolat 👍 also my first time contributing to OSS projects

**Comment by Variable2016** [comment]
Wow !
Good to hear this is your first contribution.
Happy Coding. :hugs:

**Pull request merged**
